### ISSUE TITLE
brainstorm new ideas/enhancements

### ISSUE THREAD

**Issue by szuelzke** [AshtonCorsello/Marine-Mania#103]
Done: when team comes up with ideas to improve UI and game. add complexity

**Comment by Cup00joe** [comment]
double shot

speed

radio projectile

blast 

random
 all these for possible powerups

**Comment by Cup00joe** [comment]
rocks that cant take damage and must be dodged

**Comment by Cup00joe** [comment]
general obsticles in the terrain
