### ISSUE TITLE
agree on enemy 2 concept and features

### ISSUE THREAD

**Issue by szuelzke** [AshtonCorsello/Marine-Mania#105]
Done: when team agrees when what enemy 2 should be and do

**Comment by szuelzke** [comment]
thinking an enemy that stays at the top of the screen and shoots its own projectiles, maybe with multiple hit points

**Comment by Cup00joe** [comment]
maybe it stays at the top and pauses before rushing down very quickly

**Comment by CJ-Varga** [comment]
I think either way it should send a threat directly at the player, either its own projectile or itself, to encourage movement. I like the idea of the enemy staying at the top and shooting its own projectiles
