### ISSUE TITLE
Designs for enemies (1 and 2)

### ISSUE THREAD

**Issue by tbaker60** [AshtonCorsello/Marine-Mania#117]

**Comment by rkilmer3** [comment]
Here's a few design ideas we can use for different enemies:
1. An enemy that will fly in to the screen, stop in a space and shot a projectile before flying away (enemy is removed from the array when it flies away)
2. An enemy that has multiple hit points but is slow moving and has a larger size compared to most enemies.
3. An enemy that will appear on screen, drift slowly to a position, before telegraphing a charge towards the player character's current position. Should stop tracking the player when it has started it's charge.

**Comment by tbaker60** [comment]
> Here's a few design ideas we can use for different enemies:
> 
> 1. An enemy that will fly in to the screen, stop in a space and shot a projectile before flying away (enemy is removed from the array when it flies away)
> 2. An enemy that has multiple hit points but is slow moving and has a larger size compared to most enemies.
> 3. An enemy that will appear on screen, drift slowly to a position, before telegraphing a charge towards the player character's current position. Should stop tracking the player when it has started it's charge.

I think I made a good shark guy design for this second idea, he'll be a little bigger. We can make some kind of like a pelican guy for the 1st idea
